language: node_js
node_js:
  - "lts/*"
script:
  - npm run build.data
  - npm run build.site
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  target-branch: master
  verbose: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = cron
