theme: jekyll-theme-architect
url: https://apis.guru
site:
  url: https://apis.guru
show_downloads: true
collections_dir: /
collections:
  posts:
    hidden: true
  APIs:
    output: true
    slug: apis
    name: APIs
    hidden: false
    permalink: /:collection/:path
